### ISSUE TITLE
Master doesn't build with the rust toolchain in 20.09 release

### ISSUE THREAD

**Issue by antifuchs** [serokell/deploy-rs#27]
I was surprised to find that the latest HEAD of deploy-rs doesn't build with rust 1.45.2, the version that's in the 20.09 release:

```
:;    cargo +1.45.2 test
   Compiling smol_str v0.1.17
   Compiling thin-dst v1.1.0
   Compiling rustc-hash v1.1.0
   Compiling text_unit v0.1.10
   Compiling cbitset v0.2.0
error[E0658]: `while` is not allowed in a `const fn`
  --> /Users/asf/.cargo/registry/src/github.com-1ecc6299db9ec823/smol_str-0.1.17/src/lib.rs:58:9
   |
58 | /         while i < text.len() {
59 | |             buf[i] = text.as_bytes()[i];
60 | |             i += 1
61 | |         }
   | |_________^
   |
   = note: see issue #52000 <https://github.com/rust-lang/rust/issues/52000> for more information

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `smol_str`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

Looks like smol_str (pulled in by rowan, via rnix) is using const fn's in a slightly too-modern way.
